// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pro219.DAL.Context;

#nullable disable

namespace Pro219.DAL.Migrations
{
    [DbContext(typeof(ClothesDbContext))]
    [Migration("20251119022722_DATN")]
    partial class DATN
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pro219.DAL.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("OtherInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Hồ Chí Minh",
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Delete = false,
                            District = "Quận 1",
                            FullName = "Nguyễn Văn An",
                            IsDefault = true,
                            OtherInfo = "Chung cư ABC, căn hộ 4B",
                            Phone = "0912345678",
                            Status = (byte)1,
                            Street = "123 Đường Nguyễn Huệ"
                        },
                        new
                        {
                            Id = 2,
                            City = "Hà Nội",
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Delete = false,
                            District = "Quận Ba Đình",
                            FullName = "Trần Thị Bình",
                            IsDefault = true,
                            Phone = "0987654321",
                            Status = (byte)1,
                            Street = "456 Đường Lê Lợi"
                        },
                        new
                        {
                            Id = 3,
                            City = "Hồ Chí Minh",
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Delete = false,
                            District = "Quận 5",
                            FullName = "Nguyễn Văn An",
                            IsDefault = false,
                            OtherInfo = "Nhà riêng",
                            Phone = "0912345678",
                            Status = (byte)1,
                            Street = "789 Đường Trần Hưng Đạo"
                        },
                        new
                        {
                            Id = 4,
                            City = "Đà Nẵng",
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            Delete = false,
                            District = "Quận Hải Châu",
                            FullName = "Lê Minh Cường",
                            IsDefault = true,
                            Phone = "0901234567",
                            Status = (byte)1,
                            Street = "321 Đường Hoàng Diệu"
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Brand");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Thương hiệu thể thao hàng đầu thế giới",
                            Name = "Nike",
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Thương hiệu thời trang thể thao nổi tiếng",
                            Name = "Adidas",
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Thương hiệu thời trang thể thao đẳng cấp",
                            Name = "Puma",
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Thương hiệu thời trang Nhật Bản",
                            Name = "Uniqlo",
                            Status = (byte)1,
                            UpdateBy = "admin"
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Cart");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Delete = false,
                            Status = (byte)1,
                            UpdateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Delete = false,
                            Status = (byte)1,
                            UpdateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            Delete = false,
                            Status = (byte)1,
                            UpdateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSelectedForCheckout")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("VariantId");

                    b.ToTable("CartItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CartId = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            IsSelectedForCheckout = true,
                            Quantity = 2,
                            Status = (byte)1,
                            UnitPrice = 299000m,
                            VariantId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CartId = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            IsSelectedForCheckout = false,
                            Quantity = 1,
                            Status = (byte)1,
                            UnitPrice = 799000m,
                            VariantId = 4
                        },
                        new
                        {
                            Id = 3,
                            AddedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CartId = 2,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            IsSelectedForCheckout = true,
                            Quantity = 1,
                            Status = (byte)1,
                            UnitPrice = 399000m,
                            VariantId = 6
                        },
                        new
                        {
                            Id = 4,
                            AddedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CartId = 3,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            IsSelectedForCheckout = true,
                            Quantity = 1,
                            Status = (byte)1,
                            UnitPrice = 499000m,
                            VariantId = 7
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Thời trang nam",
                            Name = "Nam",
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Thời trang nữ",
                            Name = "Nữ",
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Áo thun nam nữ",
                            Name = "Áo thun",
                            ParentCategoryId = 1,
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Quần jean nam nữ",
                            Name = "Quần jean",
                            ParentCategoryId = 1,
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Áo sơ mi công sở",
                            Name = "Áo sơ mi",
                            ParentCategoryId = 1,
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 6,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Váy nữ",
                            Name = "Váy",
                            ParentCategoryId = 2,
                            Status = (byte)1,
                            UpdateBy = "admin"
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HexCode")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Color");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            HexCode = "#FF0000",
                            Name = "Đỏ",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            HexCode = "#0000FF",
                            Name = "Xanh dương",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            HexCode = "#000000",
                            Name = "Đen",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            HexCode = "#FFFFFF",
                            Name = "Trắng",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            HexCode = "#00FF00",
                            Name = "Xanh lá",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 6,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            HexCode = "#808080",
                            Name = "Xám",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 7,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            HexCode = "#FFC0CB",
                            Name = "Hồng",
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Email = "nguyenvanan@example.com",
                            FullName = "Nguyễn Văn An",
                            PasswordHash = "b855e41c5c5f5061ecba4fd8613a7760",
                            PhoneNumber = "0912345678",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1992, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Email = "tranthibinh@example.com",
                            FullName = "Trần Thị Bình",
                            PasswordHash = "b855e41c5c5f5061ecba4fd8613a7760",
                            PhoneNumber = "0987654321",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1988, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Email = "leminhcuong@example.com",
                            FullName = "Lê Minh Cường",
                            PasswordHash = "b855e41c5c5f5061ecba4fd8613a7760",
                            PhoneNumber = "0901234567",
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.DiscountCode", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MinOrderValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DiscountId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupon");

                    b.HasData(
                        new
                        {
                            DiscountId = 1,
                            Code = "MUAHHE20",
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            DiscountType = "Percentage",
                            EndDate = new DateTime(2024, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MinOrderValue = 500000m,
                            StartDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = (byte)1,
                            UpdateBy = "admin",
                            Value = 20m
                        },
                        new
                        {
                            DiscountId = 2,
                            Code = "CHAO10",
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            DiscountType = "Percentage",
                            EndDate = new DateTime(2024, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MinOrderValue = 300000m,
                            StartDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = (byte)1,
                            UpdateBy = "admin",
                            Value = 10m
                        },
                        new
                        {
                            DiscountId = 3,
                            Code = "BLACKFRIDAY30",
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            DiscountType = "Percentage",
                            EndDate = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            MinOrderValue = 1000000m,
                            StartDate = new DateTime(2024, 11, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = (byte)1,
                            UpdateBy = "admin",
                            Value = 30m
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.InventoryLog", b =>
                {
                    b.Property<int>("InventoryLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryLogId"));

                    b.Property<int>("ChangeQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("InventoryLogId");

                    b.HasIndex("VariantId");

                    b.ToTable("InventoryLog");

                    b.HasData(
                        new
                        {
                            InventoryLogId = 1,
                            ChangeQuantity = 50,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Reason = "Nhập kho ban đầu",
                            Status = (byte)1,
                            VariantId = 1
                        },
                        new
                        {
                            InventoryLogId = 2,
                            ChangeQuantity = 30,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Reason = "Nhập kho ban đầu",
                            Status = (byte)1,
                            VariantId = 2
                        },
                        new
                        {
                            InventoryLogId = 3,
                            ChangeQuantity = 40,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Reason = "Nhập kho ban đầu",
                            Status = (byte)1,
                            VariantId = 3
                        },
                        new
                        {
                            InventoryLogId = 4,
                            ChangeQuantity = 25,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Reason = "Nhập kho ban đầu",
                            Status = (byte)1,
                            VariantId = 4
                        },
                        new
                        {
                            InventoryLogId = 5,
                            ChangeQuantity = 20,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Reason = "Nhập kho ban đầu",
                            Status = (byte)1,
                            VariantId = 5
                        },
                        new
                        {
                            InventoryLogId = 6,
                            ChangeQuantity = 35,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Reason = "Nhập kho ban đầu",
                            Status = (byte)1,
                            VariantId = 6
                        },
                        new
                        {
                            InventoryLogId = 7,
                            ChangeQuantity = 15,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Reason = "Nhập kho ban đầu",
                            Status = (byte)1,
                            VariantId = 7
                        },
                        new
                        {
                            InventoryLogId = 8,
                            ChangeQuantity = 18,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Reason = "Nhập kho ban đầu",
                            Status = (byte)1,
                            VariantId = 8
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Delete = false,
                            DiscountAmount = 279400m,
                            DiscountId = 1,
                            FinalAmount = 1117600m,
                            LastUpdate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderCode = "DH001",
                            OrderDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Đang xử lý",
                            PaymentMethodId = 1,
                            PaymentStatus = "Chờ thanh toán",
                            ShippingAddressId = 1,
                            Status = (byte)1,
                            TotalAmount = 1397000m,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            OrderId = 2,
                            CreateAt = new DateTime(2024, 1, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Delete = false,
                            DiscountAmount = 0m,
                            FinalAmount = 399000m,
                            LastUpdate = new DateTime(2024, 1, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderCode = "DH002",
                            OrderDate = new DateTime(2024, 1, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Đã giao hàng",
                            PaymentMethodId = 2,
                            PaymentStatus = "Đã thanh toán",
                            ShippingAddressId = 2,
                            Status = (byte)1,
                            TotalAmount = 399000m,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            OrderId = 3,
                            CreateAt = new DateTime(2024, 1, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            Delete = false,
                            DiscountAmount = 49900m,
                            DiscountId = 2,
                            FinalAmount = 449100m,
                            LastUpdate = new DateTime(2024, 1, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderCode = "DH003",
                            OrderDate = new DateTime(2024, 1, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Đang vận chuyển",
                            PaymentMethodId = 4,
                            PaymentStatus = "Đã thanh toán",
                            ShippingAddressId = 4,
                            Status = (byte)1,
                            TotalAmount = 499000m,
                            UpdateBy = "admin"
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderItem");

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            OrderId = 1,
                            ProductVariantId = 1,
                            Quantity = 2,
                            Status = (byte)1,
                            Subtotal = 598000m,
                            UnitPrice = 299000m
                        },
                        new
                        {
                            OrderItemId = 2,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            OrderId = 1,
                            ProductVariantId = 4,
                            Quantity = 1,
                            Status = (byte)1,
                            Subtotal = 799000m,
                            UnitPrice = 799000m
                        },
                        new
                        {
                            OrderItemId = 3,
                            CreateAt = new DateTime(2024, 1, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            OrderId = 2,
                            ProductVariantId = 6,
                            Quantity = 1,
                            Status = (byte)1,
                            Subtotal = 399000m,
                            UnitPrice = 399000m
                        },
                        new
                        {
                            OrderItemId = 4,
                            CreateAt = new DateTime(2024, 1, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            OrderId = 3,
                            ProductVariantId = 7,
                            Quantity = 1,
                            Status = (byte)1,
                            Subtotal = 499000m,
                            UnitPrice = 499000m
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethod");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Thanh toán bằng tiền mặt khi nhận hàng",
                            IsActive = true,
                            Name = "Thanh toán khi nhận hàng",
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Thanh toán bằng thẻ tín dụng",
                            IsActive = true,
                            Name = "Thẻ tín dụng",
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Chuyển khoản qua ngân hàng",
                            IsActive = true,
                            Name = "Chuyển khoản ngân hàng",
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Thanh toán qua ví điện tử (MoMo, ZaloPay)",
                            IsActive = true,
                            Name = "Ví điện tử",
                            Status = (byte)1,
                            UpdateBy = "admin"
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SaleId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 299000m,
                            BrandId = 1,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Áo thun nam chất liệu cotton mềm mại, thoáng mát, phù hợp mặc hàng ngày",
                            Name = "Áo thun nam Nike cổ tròn",
                            SaleId = 1,
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 799000m,
                            BrandId = 2,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Quần jean nam kiểu dáng slim fit, chất liệu denim cao cấp, co giãn tốt",
                            Name = "Quần jean nam Adidas slim fit",
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 399000m,
                            BrandId = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Áo thun thể thao thấm hút mồ hôi tốt, phù hợp tập luyện và vận động",
                            Name = "Áo thun thể thao Puma",
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 499000m,
                            BrandId = 4,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Áo sơ mi nam công sở, chất liệu cotton lụa, form dáng đẹp",
                            Name = "Áo sơ mi nam Uniqlo",
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 599000m,
                            BrandId = 2,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Váy nữ thể thao, chất liệu thấm hút mồ hôi, thiết kế năng động",
                            Name = "Váy nữ Adidas",
                            SaleId = 1,
                            Status = (byte)1,
                            UpdateBy = "admin"
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ProductImage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            ImageUrl = "/images/products/ao-thun-nike-do-m-1.jpg",
                            IsMain = true,
                            ProductId = 1,
                            ProductVariantId = 1,
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            ImageUrl = "/images/products/ao-thun-nike-do-m-2.jpg",
                            IsMain = false,
                            ProductId = 1,
                            ProductVariantId = 1,
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            ImageUrl = "/images/products/quan-jean-adidas-den-m-1.jpg",
                            IsMain = true,
                            ProductId = 2,
                            ProductVariantId = 4,
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            ImageUrl = "/images/products/ao-thun-puma-trang-s-1.jpg",
                            IsMain = true,
                            ProductId = 3,
                            ProductVariantId = 6,
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            ImageUrl = "/images/products/ao-so-mi-uniqlo-trang-m-1.jpg",
                            IsMain = true,
                            ProductId = 4,
                            ProductVariantId = 7,
                            Status = (byte)1,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 6,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            ImageUrl = "/images/products/vay-nu-adidas-hong-m-1.jpg",
                            IsMain = true,
                            ProductId = 5,
                            ProductVariantId = 8,
                            Status = (byte)1,
                            UpdateBy = "admin"
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArrivalTime")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SizeId")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("SizeId");

                    b.ToTable("ProductVariant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorId = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            IsActive = true,
                            Price = 299000m,
                            ProductId = 1,
                            SKU = "NKE-TSH-RED-M",
                            SizeId = 2,
                            Status = (byte)1,
                            StockQuantity = 50,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 2,
                            ColorId = 2,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            IsActive = true,
                            Price = 299000m,
                            ProductId = 1,
                            SKU = "NKE-TSH-BLU-L",
                            SizeId = 3,
                            Status = (byte)1,
                            StockQuantity = 30,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 3,
                            ColorId = 3,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            IsActive = true,
                            Price = 299000m,
                            ProductId = 1,
                            SKU = "NKE-TSH-BLK-M",
                            SizeId = 2,
                            Status = (byte)1,
                            StockQuantity = 40,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 4,
                            ColorId = 3,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            IsActive = true,
                            Price = 799000m,
                            ProductId = 2,
                            SKU = "ADD-JNS-BLK-M",
                            SizeId = 2,
                            Status = (byte)1,
                            StockQuantity = 25,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 5,
                            ColorId = 6,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            IsActive = true,
                            Price = 799000m,
                            ProductId = 2,
                            SKU = "ADD-JNS-GRY-L",
                            SizeId = 3,
                            Status = (byte)1,
                            StockQuantity = 20,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 6,
                            ColorId = 4,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            IsActive = true,
                            Price = 399000m,
                            ProductId = 3,
                            SKU = "PMA-TSH-WHT-S",
                            SizeId = 1,
                            Status = (byte)1,
                            StockQuantity = 35,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 7,
                            ColorId = 4,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            IsActive = true,
                            Price = 499000m,
                            ProductId = 4,
                            SKU = "UNQ-SHT-WHT-M",
                            SizeId = 2,
                            Status = (byte)1,
                            StockQuantity = 15,
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 8,
                            ColorId = 7,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            IsActive = true,
                            Price = 599000m,
                            ProductId = 5,
                            SKU = "ADD-DRS-PNK-M",
                            SizeId = 2,
                            Status = (byte)1,
                            StockQuantity = 18,
                            UpdateBy = "admin"
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.Review", b =>
                {
                    b.Property<int>("UniqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UniqueID"));

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Overall")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UniqueID");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            UniqueID = 1,
                            Content = "Áo rất mềm mại và thoáng mát, chất lượng đúng như mô tả. Tôi rất hài lòng với sản phẩm này!",
                            CreatedAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Delete = false,
                            Overall = 5,
                            ProductId = 1,
                            Status = (byte)1,
                            Title = "Chất lượng tốt"
                        },
                        new
                        {
                            UniqueID = 2,
                            Content = "Quần jean vừa vặn, chất liệu tốt, mặc rất đẹp. Sẽ mua thêm màu khác!",
                            CreatedAt = new DateTime(2024, 1, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Delete = false,
                            Overall = 5,
                            ProductId = 2,
                            Status = (byte)1,
                            Title = "Vừa vặn hoàn hảo"
                        },
                        new
                        {
                            UniqueID = 3,
                            Content = "Áo thấm hút mồ hôi tốt, mặc tập gym rất thoải mái. Đáng giá tiền!",
                            CreatedAt = new DateTime(2024, 1, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Delete = false,
                            Overall = 4,
                            ProductId = 3,
                            Status = (byte)1,
                            Title = "Phù hợp tập thể thao"
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("SaleValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Sale");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Giảm giá mùa hè cho tất cả sản phẩm",
                            EndDate = new DateTime(2024, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Khuyến mãi mùa hè",
                            SaleValue = 20m,
                            StartDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = (byte)1,
                            Type = "Percentage",
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Giảm giá mùa đông",
                            EndDate = new DateTime(2024, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Khuyến mãi mùa đông",
                            SaleValue = 15m,
                            StartDate = new DateTime(2024, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = (byte)1,
                            Type = "Percentage",
                            UpdateBy = "admin"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Description = "Siêu sale Black Friday",
                            EndDate = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Khuyến mãi Black Friday",
                            SaleValue = 30m,
                            StartDate = new DateTime(2024, 11, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = (byte)1,
                            Type = "Percentage",
                            UpdateBy = "admin"
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Size");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Name = "S",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Name = "M",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Name = "L",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Name = "XL",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Delete = false,
                            Name = "XXL",
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "26dc318942685872cf79c5eb96c9bb13",
                            Role = "Admin",
                            Status = (byte)1,
                            UserName = "admin"
                        },
                        new
                        {
                            UserID = 2,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "26dc318942685872cf79c5eb96c9bb13",
                            Role = "Manager",
                            Status = (byte)1,
                            UserName = "manager"
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("Wishlist");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Delete = false,
                            ProductVariantId = 2,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Delete = false,
                            ProductVariantId = 6,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Delete = false,
                            ProductVariantId = 1,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            Delete = false,
                            ProductVariantId = 5,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            Delete = false,
                            ProductVariantId = 8,
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("Pro219.DAL.Models.Address", b =>
                {
                    b.HasOne("Pro219.DAL.Models.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Cart", b =>
                {
                    b.HasOne("Pro219.DAL.Models.Customer", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Pro219.DAL.Models.CartItem", b =>
                {
                    b.HasOne("Pro219.DAL.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pro219.DAL.Models.ProductVariant", "ProductVariant")
                        .WithMany("CartItems")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Category", b =>
                {
                    b.HasOne("Pro219.DAL.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Pro219.DAL.Models.InventoryLog", b =>
                {
                    b.HasOne("Pro219.DAL.Models.ProductVariant", "ProductVariant")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Order", b =>
                {
                    b.HasOne("Pro219.DAL.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pro219.DAL.Models.DiscountCode", "DiscountCode")
                        .WithMany("Orders")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pro219.DAL.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pro219.DAL.Models.Address", "ShippingAddress")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DiscountCode");

                    b.Navigation("PaymentMethod");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("Pro219.DAL.Models.OrderItem", b =>
                {
                    b.HasOne("Pro219.DAL.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pro219.DAL.Models.ProductVariant", "ProductVariant")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Product", b =>
                {
                    b.HasOne("Pro219.DAL.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pro219.DAL.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pro219.DAL.Models.Sale", "Sale")
                        .WithMany("Products")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Pro219.DAL.Models.ProductImage", b =>
                {
                    b.HasOne("Pro219.DAL.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pro219.DAL.Models.ProductVariant", "ProductVariant")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Pro219.DAL.Models.ProductVariant", b =>
                {
                    b.HasOne("Pro219.DAL.Models.Color", "Color")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pro219.DAL.Models.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pro219.DAL.Models.Size", "Size")
                        .WithMany("ProductVariants")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Review", b =>
                {
                    b.HasOne("Pro219.DAL.Models.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pro219.DAL.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Wishlist", b =>
                {
                    b.HasOne("Pro219.DAL.Models.Customer", "Customer")
                        .WithMany("Wishlists")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pro219.DAL.Models.ProductVariant", "ProductVariant")
                        .WithMany("Wishlists")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Color", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("Pro219.DAL.Models.DiscountCode", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Pro219.DAL.Models.PaymentMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("ProductVariants");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Pro219.DAL.Models.ProductVariant", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("InventoryLogs");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductImages");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Sale", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Pro219.DAL.Models.Size", b =>
                {
                    b.Navigation("ProductVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
